### PR TITLE
cc() works under R_DEFAULT_PACKAGES=NULL

### LINKED ISSUE #6056: cc() assumes NAMESPACE import* entries are already fulfilled
Thus `cc()` doesn't work under `R_DEFAULT_PACKAGES=NULL` since package usages of base functions may not resolve correctly.

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #6056

### CODE REVIEW

File: R/AllS4.R [hunk 1]
```diff
@@ -3,21 +3,21 @@ if ("package:data.table" %in% search()) stopf("data.table package loaded. When d
 
 ## Allows data.table to be defined as an object of an S4 class,
 ## or even have data.table be a super class of an S4 class.
-setOldClass(c('data.frame'))
-setOldClass(c('data.table', 'data.frame'))
+methods::setOldClass(c('data.frame'))
```
Comment (jangorecki) [inline R/AllS4.R:6]: I would just import them once at start of the script by

setOldClass = methods::setOldClass

Comment (MichaelChirico) [reply R/AllS4.R:6]: that has the effect of basically making this `importFrom(methods, setOldClass)`, whereas `setOldClass()` is only a build-time dependency and not needed by the installed package at all.

**Review by jangorecki — APPROVED** [review]
