### PR TITLE
More robust detection of bzip2 magic number

### LINKED ISSUE #6304: fread bug in v1.15.4 when reading a CSV with no headers and first variable is BZh
fread produces an error or incorrect results when the first variable in a csv file with no headers is `BZh`. 
- In this case, `fread()` thinks that the file is a bgz file and attempts to process it accordingly via R.utils package. 
- It generates an error message to install r.utils if not installed
- It generates an empty file error if R.utils is installed

fread runs as expected if the data have headers. data.table v1.14.8 also runs as expected.

This looks to be related to the issue in #5461 and the related changes in PR #5474 and is triggered by matching against `bz2_signature` in `fread()`.

# Reproducible example

```
library(data.table)  # v 1.15.4

# these all error ----;
dt_out <- data.table(c1 = "BZh")
fwrite(dt_out, "c:/gtemp/tem1.csv", col.names = FALSE)
(dt_in <- fread("c:/gtemp/tem1.csv"))
# error if R.utils not installed:
# Error: To read gz and bz2 files directly, fread() requires 'R.utils' package which cannot be found. Please install 'R.utils' using 'install.packages('R.utils')'.

# Error if R.utils is installed:
# Error in fread("c:/gtemp/tem1.csv") : 
#   File is empty: C:\Users\grain\AppData\Local\Temp\RtmpmKTA65\file33a84c417794

(dt_in <- fread(file = "c:/gtemp/tem1.csv"))

(dt_in <- fread(file = "c:/gtemp/tem1.csv", header = FALSE))


dt_out <- data.table(c1 = c("BZh", "BZh"))
fwrite(dt_out, "c:/gtemp/tem1.csv", col.names = FALSE)
(dt_in <- fread(file = "c:/gtemp/tem1.csv", header = FALSE))

dt_out <- data.table(c1 = c("BZh"), c2 = "Bzh")
fwrite(dt_out, "c:/gtemp/tem1.csv", col.names = FALSE)
(dt_in <- fread(file = "c:/gtemp/tem1.csv", header = FALSE))

dt_out <- data.table(c1 = c("BZh", "BZh", "BZ", "GZ"), c2 = c("Bzh", "Bzh", "Bzh", "Bzh"))
fwrite(dt_out, "c:/gtemp/tem1.csv", col.names = FALSE)
(dt_in <- fread(file = "c:/gtemp/tem1.csv", header = FALSE))

# this works ----
# these all work ----;
dt_out <- data.table(c1 = "BZh")
fwrite(dt_out, "c:/gtemp/tem1.csv", col.names = TRUE)
(dt_in <- fread("c:/gtemp/tem1.csv"))

```

# Output of sessionInfo()

```
R version 4.4.1 (2024-06-14 ucrt)
Platform: x86_64-w64-mingw32/x64
Running under: Windows 10 x64 (build 19045)

Matrix products: default


locale:
[1] LC_COLLATE=English_Ireland.utf8  LC_CTYPE=English_Ireland.utf8    LC_MONETARY=English_Ireland.utf8 LC_NUMERIC=C                     LC_TIME=English_Ireland.utf8    

time zone: Europe/Dublin
tzcode source: internal

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] data.table_1.15.4

loaded via a namespace (and not attached):
[1] compiler_4.4.1    parallel_4.4.1    tools_4.4.1       R.methodsS3_1.8.2 R.utils_2.12.3    R.oo_1.26.0 
```

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #6304

Also took the opportunity to factor out some helpers for easier maintenance/readability. That could be split to its own precursor PR if so desired.

We _could_ extend `is_bzip()` to also look for "raw pi" (`as.raw(c(0x31, 0x41, 0x59, 0x26, 0x53, 0x59))`) in the 5th-10th bytes, but skip that for now. The example seems pretty pathological already.

Also, I don't think that _any_ of our `test_R.utils` tests have been checking the "infer from magic number" functionality from `fread()`, so this PR also adds some nice regression coverage for this behavior.

### CODE REVIEW

File: R/fread.R [hunk 1]
```diff
@@ -361,6 +358,30 @@ yaml=FALSE, autostart=NA, tmpdir=tempdir(), tz="UTC")
...
+# https://en.wikipedia.org/wiki/Gzip#File_format
+# not checked: remaining 8 bytes of header
+is_gzip = function(file_signature) {
+  identical(file_signature[1:2], known_signatures$gzip)
+}
+
+# https://en.wikipedia.org/wiki/Bzip2#File_format
+is_bzip = function(file_signature) {
+  identical(file_signature[1:3], known_signatures$bzip) &&
+    isTRUE(file_signature[4L] %in% charToRaw('123456789')) # for #6304
```
Comment (ben-schwen) [inline R/fread.R:382]: OK but now we shift the problem from files starting with `BZh` to files starting with `BZh1`, `BZh2`, .. right?

Comment (MichaelChirico) [reply R/fread.R:382]: yes... seems it's ultimately unavoidable. there are 6 more "known" bytes we can check but I skipped for now.

**Comment by MichaelChirico** [comment]
> Not sure we really need the `fread(header=TRUE)` test here, but I guess it can't hurt.

yea the problem as diagnosed it's kinda silly. but wanted to keep some examples close to OP's report, that way we're ironclad sure we've closed the issue & it'll stay closed.
