### PR TITLE
Fixing bug on assigning with 0 row matches

### LINKED ISSUE #2829: DT[j ,c("COL1", "NEW_COL"):=list(COL2, newValue)] returns error if j does not match
The below script illustrates the issue

```
DT <- data.table(
COL_INT = 1L,
COL_INT_2 = 5L,
)

# Works
DT[COL_INT == 0L, c("COL_INT", "NEW_COL"):=list(9L, "Test")]

# Does not work
DT[COL_INT == 0L, c("COL_INT", "NEW_COL"):=list(COL_INT_2, "Test")]
```

### PR DESCRIPTION
**Pull request by MarkusBonsch**
Closes #2829.
`assign.c` was modified to only throw error on 0 length RHS if `>0` rows are to be updated.
* No existing tests modified
* 1 test added

### CODE REVIEW

File: src/assign.c [hunk 1]
```diff
@@ -408,8 +409,10 @@ SEXP assign(SEXP dt, SEXP rows, SEXP cols, SEXP newcolnames, SEXP values, SEXP v
     else colnam = STRING_ELT(newcolnames,coln-length(names));
     if (coln+1 <= oldncol && isNull(thisvalue)) continue;  // delete existing column(s) afterwards, near end of this function
     if (vlen<1 && nrow>0) {
-      if (coln+1 <= oldncol) {
-        error("RHS of assignment to existing column '%s' is zero length but not NULL. If you intend to delete the column use NULL. Otherwise, the RHS must have length > 0; e.g., NA_integer_. If you are trying to change the column type to be an empty list column then, as with all column type changes, provide a full length RHS vector such as vector('list',nrow(DT)); i.e., 'plonk' in the new column.", CHAR(STRING_ELT(names,coln)));
+      if (coln+1 <= oldncol) { 
+        if(numToDo > 0){ //fixes #2829
```
Comment (mattdowle) [inline src/assign.c]: It took me a while to grok numToDo, but yes.  Looks good.  Could if be one if rather than two? 
`if (coln+1<=oldncol && numToDo>0) {  // numToDo fixes #2829. See test 1911`

File: NEWS.md [hunk 2]
```diff
@@ -4,7 +4,7 @@
 ### Changes in v1.11.3  (in development)
 
 #### BUG FIXES
-
+1. Fixed bug where assignment with 0 matching rows threw error [#2829](https://github.com/Rdatatable/data.table/issues/2829). Thanks to @cguill95 for reporting and to @MarkusBonsch for fixing.
```
[the remark this answers is not in the document]
Comment (MarkusBonsch) [reply NEWS.md]: Perfect, thanks! I have changed it in my latest commit.

File: src/assign.c (hunk 1 above)
Comment (MarkusBonsch) [reply src/assign.c]: It can be changed, but then the `else if` statement below needs modification: `else if(coln+1 > oldncol && TYPEOF(thisvalue)!=VECSXP)`. I think, this makes sense and have implemented it in the latest commit.

**Comment by MarkusBonsch** [comment]
AppVeyor complains about memory exhausted at test 1879.6. I guess this has nothing to do with my PR, but I don't know, how to retrigger the tests.

**Comment by jangorecki** [comment]
@MarkusBonsch you have to access appveyor, when creating account and using authentication with github you should have permission to restart builds.

File: src/assign.c [hunk 3]
```diff
@@ -408,9 +409,9 @@ SEXP assign(SEXP dt, SEXP rows, SEXP cols, SEXP newcolnames, SEXP values, SEXP v
...
     if (vlen<1 && nrow>0) {
-      if (coln+1 <= oldncol) {
-        error("RHS of assignment to existing column '%s' is zero length but not NULL. If you intend to delete the column use NULL. Otherwise, the RHS must have length > 0; e.g., NA_integer_. If you are trying to change the column type to be an empty list column then, as with all column type changes, provide a full length RHS vector such as vector('list',nrow(DT)); i.e., 'plonk' in the new column.", CHAR(STRING_ELT(names,coln)));
-      } else if (TYPEOF(thisvalue)!=VECSXP) {  // list() is ok for new columns
+      if (coln+1 <= oldncol && numToDo > 0) { // numToDo > 0 fixes #2829, see test 1911
+          error("RHS of assignment to existing column '%s' is zero length but not NULL. If you intend to delete the column use NULL. Otherwise, the RHS must have length > 0; e.g., NA_integer_. If you are trying to change the column type to be an empty list column then, as with all column type changes, provide a full length RHS vector such as vector('list',nrow(DT)); i.e., 'plonk' in the new column.", CHAR(STRING_ELT(names,coln)));
```
Comment (jangorecki) [inline src/assign.c]: we use 2 spaces indention

File: NEWS.md [hunk 4]
```diff
@@ -4,6 +4,7 @@
 ### Changes in v1.11.3  (in development)
 
 #### BUG FIXES
+1. Empty RHS of := is no longer an error when the i clause returns no rows to assign to anyway, [#2829](https://github.com/Rdatatable/data.table/issues/2829). Thanks to @cguill95 for reporting and to @MarkusBonsch for fixing.
```
Comment (jangorecki) [inline NEWS.md]: empty line should separate header and first item
