### PR TITLE
only coerce UTF8 factors if needed in memrecycle

### LINKED ISSUE #7404: benchmark regression
I just had a look at the [ducklabs benchmarks](https://duckdblabs.github.io/db-benchmark/) and it seems that there has been regression for:

max v1 - min v2 by id3
`x[, .(range_v1_v2=max(v1, na.rm=TRUE)-min(v2, na.rm=TRUE)), by=id3]`

See the xlarge instance (with 256 GB memory) and 0.5 GB dataset where it takes ~57 seconds while running instant on the 32 GB memory instance (on a previos data.table version).

Would be nice to sort this out #7401 will make this case a lot faster.

Update: I have run this locally and #7401 takes down the regression from 24 seconds to 0.297 seconds :)

### PR DESCRIPTION
**Pull request by ben-schwen**
Closes #7404

Not sure about the test since we want to essentially test for `system.time` of the test. Maybe its better to use an atime test? The added tests bombs runners by taking 2 hours with regression :(

### CODE REVIEW

File: src/assign.c [hunk 1]
```diff
@@ -755,10 +755,14 @@ const char *memrecycle(const SEXP target, const SEXP where, const int start, con
...
       SEXP sourceLevels = source;  // character source
       if (sourceIsFactor) { sourceLevels=PROTECT(getAttrib(source, R_LevelsSymbol)); protecti++; }
-      sourceLevels = PROTECT(coerceUtf8IfNeeded(sourceLevels)); protecti++;
-      if (!sourceIsFactor || !R_compute_identical(sourceLevels, targetLevels, 0)) {  // !sourceIsFactor for test 2115.6
-        const int nTargetLevels=length(targetLevels), nSourceLevels=length(sourceLevels);
+      bool needUtf8Coerce = !sourceIsFactor || !R_compute_identical(sourceLevels, targetLevels, 0);
+      if (needUtf8Coerce) {
+        sourceLevels = PROTECT(coerceUtf8IfNeeded(sourceLevels)); protecti++;
         targetLevels = PROTECT(coerceUtf8IfNeeded(targetLevels)); protecti++;
+        if (sourceIsFactor && R_compute_identical(sourceLevels, targetLevels, 0)) needUtf8Coerce = false;
```
Comment (aitap) [inline src/assign.c]: Is the `needUtf8Coerce = false` assignment covered? I've tried compiling with `-Og` and setting a breakpoint on the exact instruction setting the register to 0 and it didn't fire during `test.data.table()`. I think it might be unreachable.

The results of `R_compute_identical()` shouldn't change after `coerceUtf8IfNeeded()` because `identical()` takes encodings into account:

https://github.com/r-devel/r-svn/blob/96eee1cdda590de914d48fed05d8f0783f921da4/src/main/memory.c#L4978-L4997

This is quite convenient because a factor with levels `enc2utf8('ø')` and a factor with levels `iconv('ø', to = 'latin1')` will pass the first `R_compute_identical()` already, without any other string conversions.

**Review by aitap — APPROVED** [review]
Excellent diagnosis, thank you. Indeed, the costly calls to `need2utf8` can be gated by the levels being non-identical (which we need to test anyway).

I think this is more suitable for an atime test than a normal regression test.

File: src/assign.c (hunk 1 above)
Comment (ben-schwen) [reply src/assign.c]: Good point! I removed the unreachable code. Will add an atime test as a separate PR. I guess our current "issue" with atime tests and why we have to keep these branches alive, is that we squash when merging and hence the commits will disappear

@tdhock @Anirban166 does this sound right?

**Comment by aitap** [comment]
A workaround discussed in a different issue is to first merge the PR and then record the SHA1-hash of the merge commit in a follow-up commit instead of the HEAD of the PR branch.

**Comment by ben-schwen** [comment]
@TysonStanley this should probably be also picked for the release (since it is a regression fix for smth included in `1.17.2`)!
