### PR TITLE
lto warning fix

### LINKED ISSUE #5760: compilation warning: chmatch.c argument 1 range exceeds maximum object size
Reactivating CI detects compilation warnings:
```
lto-wrapper: warning: using serial compilation of 7 LTRANS jobs
chmatch.c:98:26: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
chmatch.c:98:26: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
```
https://gitlab.com/Rdatatable/data.table/-/jobs/5615913284

```
lto-wrapper: warning: using serial compilation of 7 LTRANS jobs
lto-wrapper: note: see the ‘-flto’ option documentation for more information
chmatch.c: In function ‘chmatchMain’:
chmatch.c:98:26: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   98 |     int *map =    (int *)calloc(tablelen+nuniq, sizeof(int));  // +nuniq to store a 0 at the end of each group
      |                          ^
/usr/include/stdlib.h:556:14: note: in a call to allocation function ‘calloc’ declared here
  556 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^
chmatch.c:98:26: warning: argument 1 range [18446744071562067968, 18446744073709551615] exceeds maximum object size 9223372036854775807 [-Walloc-size-larger-than=]
   98 |     int *map =    (int *)calloc(tablelen+nuniq, sizeof(int));  // +nuniq to store a 0 at the end of each group
      |                          ^
/usr/include/stdlib.h:556:14: note: in a call to allocation function ‘calloc’ declared here
  556 | extern void *calloc (size_t __nmemb, size_t __size)
      |              ^
```

### PR DESCRIPTION
**Pull request by jangorecki**
Closes #5760

There are 2 warnings actually, chmatch resolved by unsigned int, another by -flto=auto

### CODE REVIEW

File: src/chmatch.c [hunk 1]
```diff
@@ -95,7 +95,8 @@ static SEXP chmatchMain(SEXP x, SEXP table, int nomatch, bool chin, bool chmatch
     // For example: A,B,C,B,D,E,A,A   =>   A(TL=1),B(2),C(3),D(4),E(5)   =>   dupMap    1  2  3  5  6 | 8  7  4
     //                                                                        dupLink   7  8          |    6     (blank=0)
     int *counts = (int *)calloc(nuniq, sizeof(int));
-    int *map =    (int *)calloc(tablelen+nuniq, sizeof(int));  // +nuniq to store a 0 at the end of each group
+    unsigned int mapsize = tablelen+nuniq; // lto compilation warning #5760
+    int *map =    (int *)calloc(mapsize, sizeof(int));  // +nuniq to store a 0 at the end of each group
```
Comment (MichaelChirico) [inline src/chmatch.c:99]: comment about `+nuniq` seems orphaned

**Review by MichaelChirico — APPROVED** [review]
