### PR TITLE
Reset dec='\0' to detect numbers while dec is undecided

### LINKED ISSUE #6440: Parsing ISO8601 with microseconds in fread() broken in 1.16.0
Since 1.16.0, some data containing microsecond-precision ISO 8601 timestamps fails to parse in `fread`.

If parsed without class hints, this results in a verbatim `char` string.
If parsed with `"POSIXct"` in `colClasses`, it takes a significantly longer time on larger datasets and results in a date without time information.

# Minimal reproducible example

```r
library("data.table")
fread(text="Datetime\n2023-10-12T06:53:53.123Z")
fread(text="DatetimeExplicit\n2023-10-12T06:53:53.123Z", colClasses="POSIXct")
```

Expected output (1.15.4):
```
              Datetime
                <POSc>
1: 2023-10-12 06:53:53
      DatetimeExplicit
                <POSc>
1: 2023-10-12 06:53:53
```

Output in 1.16.0 and 1.16.99:
```
                   Datetime
                     <char>
1: 2023-10-12T06:53:53.123Z
   DatetimeExplicit
             <POSc>
1:       2023-10-12
```

# Output of `sessionInfo()`
```
> sessionInfo()
R version 4.4.1 (2024-06-14)
Platform: x86_64-pc-linux-gnu
Running under: Ubuntu 22.04.4 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C
 [9] LC_ADDRESS=C               LC_TELEPHONE=C
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C

time zone: Etc/UTC
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base

other attached packages:
[1] data.table_1.16.99

loaded via a namespace (and not attached):
[1] compiler_4.4.1 tools_4.4.1
```

# Additional observation

Not all data fails to parse. The following example works in 1.16.99, and I am not sure why:

```r
fread(text="A,B\n2023-10-12T06:53:53.123Z,2023-10-12T06:53:53.123Z")
```
```
                     A                   B
                <POSc>              <POSc>
1: 2023-10-12 06:53:53 2023-10-12 06:53:53
```

This might be why this slipped past regression tests.
In my code that broke with the update, the timestamps were a single isolated column in the middle of other types of columns.

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #6440.

`dec='\0'` is reset each time when moving on to the next _column_:

https://github.com/Rdatatable/data.table/blob/80c46a05b0f859c39c756777c207732422877a81/src/fread.c#L1250

The issue here really is isolated to timestamps with milliseconds: _within_ a column, once `dec=','` is tried & fails to parse the timestamp (as a real number), `dec=','` is left dangling --> the timestamp fails to parse. This only matters for "higher" types than real numbers where double parsing is attempted, i.e. only timestamps.

Because `IS_DEC_TYPE()` excludes timestamp on master, and hence whether a timestamp parses with `,` doesn't count to the "race" vs. `dec='.'`, the timestamp also fails to parse with `,` as the microsecond separator:

```r
fread(text="Datetime\n2023-10-12T06:53:53,123Z", sep="\t") # sep= required otherwise `,` is seen as sep in this simple example
#                    Datetime
#                      <char>
# 1: 2023-10-12T06:53:53,123Z
```

But this can be nudged to work in files with fields recognized as real numbers on `master`:
```
fread(text="x\tDatetime\n1,0\t2023-10-12T06:53:53,123Z", sep="\t")
#        x            Datetime
#    <num>              <POSc>
# 1:     1 2023-10-12 06:53:53
```

One incidental change of the PR as of now is that ISO timestamps will parse correctly with `,` as the millisecond separator; @kav2k confirmed this is OK and in fact recognized by the standard.

### CODE REVIEW

**Comment by MichaelChirico** [comment]
> My concern is data that potentially mixes separators, because even preferring , for decimal, software will likely output . for ISO timestamps (data.table itself is an example):

Oh, nice example. I think that's a follow-up issue for `fwrite()` to support.

`fread()`, in the auto-detect step, "runs a race" between `dec='.'` and `dec=','`; whichever successfully parses more fields is chosen (tie goes to `'.'`):

https://github.com/Rdatatable/data.table/blob/80c46a05b0f859c39c756777c207732422877a81/src/fread.c#L1922

I think this is "good enough". We could possibly support `dec = <vector>` to allow specifying a `dec` for each column, but I'd rather not go there, and fix `fwrite()` to avoid producing such mixtures in the first place.

> Probably not a good idea to support this though. 

Yea, no thanks 😂 

TBH it would not be _that_ hard to support (switch to double parsing here, and don't fail for missing some components), but I doubt it's common enough to be worth maintaining:

https://github.com/Rdatatable/data.table/blob/80c46a05b0f859c39c756777c207732422877a81/src/fread.c#L1032

> So this fix (which, if I understand correctly, is trying to reparse with the other separator if one fails)

Some nuance, this fix is only about the "auto-detect" phase of `fread()` which runs on a sample of lines to decide the column types. Previously (since `dec='auto'` support was added) there was no re-try on timestamps, and only `dec=','` was tried (by mistake).

**Comment by MichaelChirico** [comment]
> My concern is data that potentially mixes separators, because even preferring , for decimal, software will likely output . for ISO timestamps (data.table itself is an example):

From #6454, this point is moot from data.table -- `fwrite(dec=',')` will write timestamps with `,` :)

**Comment by MichaelChirico** [comment]
Checking in @ben-schwen, got time for a review? Would be nice to get this last part of the 1.16.2 patch submitted.

File: src/fread.c [hunk 1]
```diff
@@ -1038,7 +1038,7 @@ static void parse_iso8601_timestamp(FieldParseContext *ctx)
   if (second == NA_FLOAT64 || second < 0 || second >= 60)
     goto fail;
 
-  if (*ch == 'Z') {
+  if (*ch == 'Z') {
```
Comment (ben-schwen) [inline src/fread.c:1041]:
```suggestion
  if (*ch == 'Z') {
```

**Comment by ben-schwen** [comment]
fread(text="t\n2023-10-12T06:53:53.123Z", colClasses="nanotime") # works
fread(text="t\n2023-10-12T06:53:53,123Z", colClasses="nanotime") # does not

**Comment by MichaelChirico** [comment]
Got another "refuse to merge unrelated histories" thing here, strange. Reinstated the changes but lost the history again :\

**Comment by MichaelChirico** [comment]
> ```r
> fread(text="t\n2023-10-12T06:53:53.123Z", colClasses="nanotime") # works
> fread(text="t\n2023-10-12T06:53:53,123Z", colClasses="nanotime", sep=";") # does not
> ```

That's an R side issue:

```r
as.nanotime("2023-10-12T06:53:53,123Z")
# Error: Parse error on 2023-10-12T06:53:53,123Z
```

But I'm reminded of #6107, there may be a way to get it returned to R as `POSIXct` and then it will work:

```
as.nanotime(fread(text="t\n2023-10-12T06:53:53.123Z", colClasses="nanotime")$t)
# [1] 2023-10-12T06:53:53.123+00:00
```

Out of scope here though, filing for follow-up.

**Comment by ben-schwen** [comment]
LGTM, ty!
