### PR TITLE
Fix `onLoad` for `devtools::load_all()`

### LINKED ISSUE #5827: Loading package via `devtools::load_all()` errors
I know that we have `cc()` for recompiling and attaching the package. However, people unfamiliar with `data.table` dev might try to use `devtools::load_all()` which currently errors on loading.

```r
devtools::load_all()
#  Error in gzfile(file, "rb") : cannot open the connection
#  In addition: Warning message:
#  In gzfile(file, "rb") :
#    cannot open compressed file '', probable reason 'No such file or directory'
```

Minimal change to `.onLoad` would enable `devtools::load_all()` to also work.

### PR DESCRIPTION
**Pull request by ben-schwen**
Closes #5827

### CODE REVIEW

File: R/onLoad.R [hunk 1]
```diff
@@ -25,8 +25,8 @@
       # https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17478
       stopf("The data_table.%s version (%s) does not match the package (%s). Please close all R sessions to release the old %s and reinstall data.table in a fresh R session. The root cause is that R's package installer can in some unconfirmed circumstances leave a package in a state that is apparently functional but where new R code is calling old C code silently: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17478. Once a package is in this mismatch state it may produce wrong results silently until you next upgrade the package. Please help by adding precise circumstances to 17478 to move the status to confirmed. This mismatch between R and C code can happen with any package not just data.table. It is just that data.table has added this check.", dll, dllV, RV, toupper(dll))
     }
-    builtUsing = readRDS(system.file("Meta/package.rds",package="data.table"))$Built$R
-    if (!identical(base::getRversion()>="4.0.0", builtUsing>="4.0.0")) {
+    builtPath = system.file("Meta/package.rds",package="data.table")
```
Comment (MichaelChirico) [inline R/onLoad.R:28]:
```suggestion
    builtPath = system.file("Meta", "package.rds", package="data.table")
```

Comment (ben-schwen) [reply R/onLoad.R]: Good spot. Will try if it works on Windows though :D

File: .dev/README.md [hunk 2]
```diff
@@ -1,5 +1,14 @@
 # data.table developer
 
+## Setup
+
+One needs to set up the project path and source `.dev/cc.R` to use `cc()` conveniently. This works through creating an additional `.Rprofile` in the `data.table` directory.
```
Comment (jangorecki) [inline .dev/README.md:5]: It feels like this is required for developing DT. It is a optional helper function so should not sound like a requirement for setting up Dev environment.

Comment (TysonStanley) [reply .dev/README.md:5]: I agree. A quick change to: "An optional helper function can be accessed by setting up the project path and source ..."

**Review by TysonStanley — APPROVED** [review]

**Comment by TysonStanley** [comment]
Once the tests pass, I think this one can be merged.

File: .dev/README.md [hunk 3]
```diff
@@ -1,5 +1,15 @@
 # data.table developer
 
+## Setup
+
+To use the optional helper function `cc()`, one needs to set up the project path and source `.dev/cc.R` to use `cc()` conveniently. This works through creating an additional `.Rprofile` in the `data.table` directory.
+
+```r
+# content of ~/git/data.table/.Rprofile
```
Comment (MichaelChirico) [inline .dev/README.md:8]: I would leave out the assumed `~/git/data.table`, maybe

> content of ../.Rprofile

or

> content of .Rprofile in the package directory

File: R/onLoad.R [hunk 4]
```diff
@@ -25,8 +25,8 @@
...
       stopf("The data_table.%s version (%s) does not match the package (%s). Please close all R sessions to release the old %s and reinstall data.table in a fresh R session. The root cause is that R's package installer can in some unconfirmed circumstances leave a package in a state that is apparently functional but where new R code is calling old C code silently: https://bugs.r-project.org/bugzilla/show_bug.cgi?id=17478. Once a package is in this mismatch state it may produce wrong results silently until you next upgrade the package. Please help by adding precise circumstances to 17478 to move the status to confirmed. This mismatch between R and C code can happen with any package not just data.table. It is just that data.table has added this check.", dll, dllV, RV, toupper(dll))
     }
-    builtUsing = readRDS(system.file("Meta/package.rds",package="data.table"))$Built$R
-    if (!identical(base::getRversion()>="4.0.0", builtUsing>="4.0.0")) {
+    builtPath = system.file("Meta", "package.rds", package="data.table")
+    if (builtPath != "" && !identical(base::getRversion()>="4.0.0", (builtUsing<-readRDS(builtPath)$Built$R)>="4.0.0")) {
```
Comment (MichaelChirico) [inline R/onLoad.R:29]: looks like `getRversion()` is re-run a few times in `.onLoad()`, let's cache the output & re-use it while we're here?

```
session_r_version <- base::getRversion()
```

Or, since it's only used to check the 4.0.0 boundary, perhaps

```r
session_has_cbind_dispatch = base::getRversion() >= "4.0.0"
```

File: R/onLoad.R [hunk 5]
```diff
@@ -25,9 +26,9 @@
...
     }
-    builtUsing = readRDS(system.file("Meta/package.rds",package="data.table"))$Built$R
-    if (!identical(base::getRversion()>="4.0.0", builtUsing>="4.0.0")) {
-      stopf("This is R %s but data.table has been installed using R %s. The major version must match. Please reinstall data.table.", base::getRversion(), builtUsing)
+    builtPath = system.file("Meta", "package.rds", package="data.table")
+    if (builtPath != "" && !identical(session_r_version>="4.0.0", (builtUsing<-readRDS(builtPath)$Built$R)>="4.0.0")) {
+      stopf("This is R %s but data.table has been installed using R %s. The major version must match. Please reinstall data.table.", session_r_version, builtUsing)
```
Comment (MichaelChirico) [inline R/onLoad.R:31]:
```suggestion
    if (builtPath != "" && !identical(session_r_version>="4.0.0", (build_r_version <- readRDS(builtPath)$Built$R)>="4.0.0")) {
      stopf("This is R %s but data.table has been installed using R %s. The major version must match. Please reinstall data.table.", session_r_version, build_r_version)
```

consistent variable style

**Review by MichaelChirico — APPROVED** [review]
