### PR TITLE
to pass rchk

### LINKED ISSUE #4625: rchk results to work through
"too many states" is normal and fine. It's just where there's a line number we can tackle to try to keep rchk happy. Then when it's happier on those lines, it gets past them and gets further and maybe it'll find something else later that's more significant.

```
$ cat packages/lib/data.table/libs/*check
ERROR: too many states (abstraction error?) in function strptime_internal
ERROR: too many states (abstraction error?) in function rbindlist
ERROR: too many states (abstraction error?) in function freadMain
ERROR: too many states (abstraction error?) in function rbindlist

Function chmatchMain
  [PB] has an unsupported form of unprotect with a variable results will be incomplete /home/mdowle/build/rchk/trunk/packages/build/ek2WrWRd/data.table/src/chmatch.c:49
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /home/mdowle/build/rchk/trunk/packages/build/ek2WrWRd/data.table/src/chmatch.c:49
  [PB] has an unsupported form of unprotect with a variable results will be incomplete /home/mdowle/build/rchk/trunk/packages/build/ek2WrWRd/data.table/src/chmatch.c:127
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /home/mdowle/build/rchk/trunk/packages/build/ek2WrWRd/data.table/src/chmatch.c:127

Function fcaseR
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /home/mdowle/build/rchk/trunk/packages/build/ek2WrWRd/data.table/src/fifelse.c:344

Function measurelist
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /home/mdowle/build/rchk/trunk/packages/build/ek2WrWRd/data.table/src/fmelt.c:106

Function rbindlist
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /home/mdowle/build/rchk/trunk/packages/build/ek2WrWRd/data.table/src/rbindlist.c:531

Function shift
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /home/mdowle/build/rchk/trunk/packages/build/ek2WrWRd/data.table/src/shift.c:161
Analyzed 275 functions, traversed 3126812 states.
Library name (usually package name): datatable
Initialization function: R_init_datatable
Functions: 87
Functions: 1
Checked call to R_registerRoutines: 1
```

### PR DESCRIPTION
**Pull request by mattdowle**
Closes #4625 
Tick means rerunning `rchk` locally now passes that file.
- [x] chmatch.c
- [x] fifelse.c  Needed rework to remove the REPROTECT. Since the first value was being referenced from within the loop, I'm thinking there was a real problem there; now the first value is protected until the end of the function. Also the `l` variable was `int` and should have been `int64_t`. Found by moving variable declarations as close to usage as possible.
- [x] fmelt.c
- [x] rbindlist.c  I looked but I can't see what we can do here. I don't think 'unsupported form of unprotect' is flagged by CRAN additional checks anyway, so we can leave this one. Yes, all the notices are the same 'unsupported form of unprotect' so we could have left them all on that basis, however, I could see what we would do in the other cases so I did those ones.
- [x] shift.c  As well as passing rchk by making each case its own scope with balanced protect/unprotect within that tight local scope, this should bring a benefit in large cases by saving the heap by unprotecting as it goes along, rather than storing up all the allocations and unprotecting them all at the end.

### CODE REVIEW

File: src/fmelt.c [hunk 1]
```diff
@@ -91,19 +91,25 @@ SEXP concat(SEXP vec, SEXP idx) {
 
 // deal with measure.vars of type VECSXP
 SEXP measurelist(SEXP measure, SEXP dtnames) {
-  int i, n=length(measure), protecti=0;
```
Comment (MichaelChirico) [inline src/fmelt.c:94]: I don't really see any work done in fmelt since 1.12.8... I guess that means something upstream changed? Maybe improvements to `rchk` / R-devel changes?

Comment (mattdowle) [reply src/fmelt.c:94]: Yes, most likely `rchk` changes I'd guess. I am using latest rchk fetched yesterday from master:  https://github.com/kalibera/rchk/commits/master.

Comment (MichaelChirico) [reply src/fmelt.c:94]: Ah, definitely a version change on `llvm` sounds like a likely candidate, thanks

Comment (mattdowle) [reply src/fmelt.c:94]: Actaully, fmelt.c did come up last time and I skipped it with comments here:  https://github.com/Rdatatable/data.table/pull/3867#issuecomment-531382945.  Looks like `rchk` is getting better at not showing us the false positives, and I'm getting better at guessing how rchk likes things too.

**Comment by mattdowle** [comment]
Resolved rchk status. These remaining messages are as good as it gets currently since we push the limits of the rchk tool. This is enough to pass rchk on CRAN checks page as these particular items get filtered out by CRAN.
```
$ cat packages/lib/data.table/libs/*check
ERROR: too many states (abstraction error?) in function strptime_internal
ERROR: too many states (abstraction error?) in function rbindlist
ERROR: too many states (abstraction error?) in function freadMain
ERROR: too many states (abstraction error?) in function rbindlist

Function rbindlist
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [UP] protect stack is too deep, unprotecting all variables, results will be incomplete
  [UP] unsupported form of unprotect, unprotecting all variables, results will be incomplete /home/mdowle/build/rchk/trunk/packages/build/BgRz8GCN/data.table/src/rbindlist.c:531
Analyzed 275 functions, traversed 3481371 states.
Library name (usually package name): datatable
Initialization function: R_init_datatable
Functions: 87
Functions: 1
Checked call to R_registerRoutines: 1
```
