### PR TITLE
adapt header for cc

### LINKED ISSUE #7512: Compiler issue from siginfo_t, waitid, ...
#7428 introduced some higher compiler requirements than 1.17.0:

https://github.com/Rdatatable/data.table/blob/e455714d92b73f716913d3bdb225c90ac67e9d1c/src/utils.c#L688-L695

I get these compiler errors:

```
src/utils.c:692:3: error: use of undeclared identifier 'siginfo_t'
  692 |   siginfo_t info;
      |   ^~~~~~~~~
src/utils.c:694:15: error: call to undeclared function 'waitid'; ISO C99 and later do not support implicit function declarations [-Wimplicit-function-declaration]
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |               ^
src/utils.c:694:15: note: did you mean 'waitpid'?
.../sys/wait.h:111:16: note: 'waitpid' declared here
  111 | extern __pid_t waitpid (__pid_t __pid, int *__stat_loc, int __options);
      |                ^
src/utils.c:694:22: error: use of undeclared identifier 'P_PID'
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                      ^~~~~
src/utils.c:694:40: error: use of undeclared identifier 'info'
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                                        ^~~~
src/utils.c:694:46: error: use of undeclared identifier 'WCONTINUED'
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                                              ^~~~~~~~~~
src/utils.c:694:59: error: use of undeclared identifier 'WEXITED'
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                                                           ^~~~~~~
src/utils.c:694:79: error: use of undeclared identifier 'WNOWAIT'
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                                                                               ^~~~~~~
src/utils.c:694:89: error: use of undeclared identifier 'WSTOPPED'
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                                                                                         ^~~~~~~~
8 errors generated.
```

I fixed it by changing `-std=c11` to `-std=gnu99`, but this is a (mildly) breaking change. Can it be avoided? Or can we add more header guards to work around this / improve the mode of failure?

### PR DESCRIPTION
**Pull request by ben-schwen**
Closes #7512 

Follows #7428 since I cannot `cc()` after that

```bash
gcc -I"/usr/share/R/include" -DNDEBUG      -fopenmp  -fpic  -fopenmp -std=c11 -O3 -pipe -Wall -pedantic -Wstrict-prototypes -isystem /usr/share/R/include  -fno-common -c utils.c -o utils.o
gcc -I"/usr/share/R/include" -DNDEBUG      -fopenmp  -fpic  -fopenmp -std=c11 -O3 -pipe -Wall -pedantic -Wstrict-prototypes -isystem /usr/share/R/include  -fno-common -c vecseq.c -o vecseq.o
gcc -I"/usr/share/R/include" -DNDEBUG      -fopenmp  -fpic  -fopenmp -std=c11 -O3 -pipe -Wall -pedantic -Wstrict-prototypes -isystem /usr/share/R/include  -fno-common -c wrappers.c -o wrappers.o
utils.c: In function ‘is_direct_child’:
utils.c:692:3: error: unknown type name ‘siginfo_t’
  692 |   siginfo_t info;
      |   ^~~~~~~~~
utils.c:694:15: warning: implicit declaration of function ‘waitid’; did you mean ‘waitpid’? [-Wimplicit-function-declaration]
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |               ^~~~~~
      |               waitpid
utils.c:694:22: error: ‘P_PID’ undeclared (first use in this function)
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                      ^~~~~
utils.c:694:22: note: each undeclared identifier is reported only once for each function it appears in
utils.c:694:46: error: ‘WCONTINUED’ undeclared (first use in this function)
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                                              ^~~~~~~~~~
utils.c:694:59: error: ‘WEXITED’ undeclared (first use in this function); did you mean ‘WIFEXITED’?
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                                                           ^~~~~~~
      |                                                           WIFEXITED
utils.c:694:79: error: ‘WNOWAIT’ undeclared (first use in this function)
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                                                                               ^~~~~~~
utils.c:694:89: error: ‘WSTOPPED’ undeclared (first use in this function); did you mean ‘WIFSTOPPED’?
  694 |     pret[i] = waitid(P_PID, ppids[i], &info, WCONTINUED | WEXITED | WNOHANG | WNOWAIT | WSTOPPED) == 0;
      |                                                                                         ^~~~~~~~
      |                                                                                         WIFSTOPPED
```

### CODE REVIEW

File: src/utils.c [hunk 1]
```diff
@@ -1,4 +1,5 @@
 #ifndef _WIN32
+#  define _POSIX_C_SOURCE 200809L
```
Comment (MichaelChirico) [inline src/utils.c]:
```suggestion
#  define _POSIX_C_SOURCE 200809L // required for non-POSIX features in is_direct_child e.g. 'siginfo_t'
```

**Comment by aitap** [comment]
Manual testing shows that POSIX.1-2001 feature test macro is not enough; it has to be POSIX.1-2008 or newer.
