### PR TITLE
avoid struct move on Solaris

### LINKED ISSUE #4099: fwrite gzip on Solaris error
Now that 1.12.8 is on CRAN, we have the output from the extra tracing in #4028.
https://www.r-project.org/nosvn/R.check/r-patched-solaris-x86/data.table-00check.html
```
using R version 3.6.2 RC (2019-12-06 r77544)
using platform: i386-pc-solaris2.10 (32-bit)
using session charset: UTF-8
using option ‘--no-stop-on-test-error’
checking for file ‘data.table/DESCRIPTION’ ... OK
this is package ‘data.table’ version ‘1.12.8’
checking package namespace information ... OK
checking package dependencies ... OK
checking if this is a source package ... OK
checking if there is a namespace ... OK
checking for executable files ... OK
checking for hidden files and directories ... OK
checking for portable file names ... OK
checking for sufficient/correct file permissions ... OK
checking whether package ‘data.table’ can be installed ... OK
checking installed package size ... OK
checking package directory ... OK
checking ‘build’ directory ... OK
checking DESCRIPTION meta-information ... OK
checking top-level files ... OK
checking for left-over files ... OK
checking index information ... OK
checking package subdirectories ... OK
checking R files for non-ASCII characters ... OK
checking R files for syntax errors ... OK
checking whether the package can be loaded ... OK
checking whether the package can be loaded with stated dependencies ... OK
checking whether the package can be unloaded cleanly ... OK
checking whether the namespace can be loaded with stated dependencies ... OK
checking whether the namespace can be unloaded cleanly ... OK
checking loading without being on the library search path ... OK
checking use of S3 registration ... OK
checking dependencies in R code ... OK
checking S3 generic/method consistency ... OK
checking replacement functions ... OK
checking foreign function calls ... OK
checking R code for possible problems ... [34s/41s] OK
checking Rd files ... OK
checking Rd metadata ... OK
checking Rd cross-references ... OK
checking for missing documentation entries ... OK
checking for code/documentation mismatches ... OK
checking Rd \usage sections ... OK
checking Rd contents ... OK
checking for unstated dependencies in examples ... OK
checking line endings in shell scripts ... OK
checking line endings in C/C++/Fortran sources/headers ... OK
checking line endings in Makefiles ... OK
checking compilation flags in Makevars ... OK
checking for GNU extensions in Makefiles ... OK
checking for portable use of $(BLAS_LIBS) and $(LAPACK_LIBS) ... OK
checking include directives in Makefiles ... OK
checking compilation flags used ... OK
checking compiled code ... OK
checking installed files from ‘inst/doc’ ... OK
checking files in ‘vignettes’ ... OK
checking examples ... OK
checking for unstated dependencies in ‘tests’ ... OK
checking tests ... [102s/115s] ERROR
  Running ‘autoprint.R’
  Comparing ‘autoprint.Rout’ to ‘autoprint.Rout.save’ ... OK
  Running ‘froll.R’ [35s/38s]
  Running ‘knitr.R’
  Comparing ‘knitr.Rout’ to ‘knitr.Rout.save’ ... OK
  Running ‘main.R’ [58s/66s]
  Running ‘nafill.R’
  Running ‘other.R’
  Running ‘types.R’
Running the tests in ‘tests/main.R’ failed.
Complete output:
  > require(data.table)
  Loading required package: data.table
  >
  > test.data.table() # runs the main test suite of 5,000+ tests in /inst/tests/tests.Rraw
  getDTthreads(verbose=TRUE):
    omp_get_num_procs() 16
    R_DATATABLE_NUM_PROCS_PERCENT unset (default 50)
    R_DATATABLE_NUM_THREADS unset
    omp_get_thread_limit() 2
    omp_get_max_threads() 2
    OMP_THREAD_LIMIT 2
    OMP_NUM_THREADS unset
    RestoreAfterFork true
    data.table is using 2 threads. See ?setDTthreads.
  test.data.table() running: /home/ripley/R/Lib32/data.table/tests/tests.Rraw.bz2
  Test 1658.421 produced 1 errors but expected 0
  Expected:
  Observed: zlib 1.2.11 (zlib.h 1.2.11) deflate() returned error -2 with z_stream->msg=="" Z_FINISH=4 Z_BLOCK=5. Please include the full output above and below this message in your data.table bug report.
  Output captured before unexpected warning/error/message:
    omp_get_num_procs() 16
    R_DATATABLE_NUM_PROCS_PERCENT unset (default 50)
    R_DATATABLE_NUM_THREADS unset
    omp_get_thread_limit() 2
    omp_get_max_threads() 2
    OMP_THREAD_LIMIT 2
    OMP_NUM_THREADS unset
    RestoreAfterFork true
    data.table is using 2 threads. See ?setDTthreads.
  No list columns are present. Setting sep2='' otherwise quote='auto' would quote fields containing sep2.
  Column writers: 3 3
  args.doRowNames=0 args.rowNames=0 doQuote=-128 args.nrow=200 args.ncol=2 eolLen=1
  maxLineLen=51. Found in 0.000s
  Writing bom (false), yaml (0 characters) and column names (true) ... deflate input stream: e15b240 39 afdc2f8 4
  deflate returned 1 with stream->total_out==24; Z_FINISH==4, Z_OK==0, Z_STREAM_END==1
  done in 0.000s
  Writing 200 rows in 1 batches of 200 rows (each buffer size 8MB, showProgress=0, nth=1)
  deflate input stream: d259448 8391193 f9f9fd8 800
  deflate returned -2 with stream->total_out==0; Z_FINISH==4, Z_OK==0, Z_STREAM_END==1
  <simpleError in fwrite(DT, file = f1 <- tempfile(fileext = ".gz"), verbose = TRUE): zlib 1.2.11 (zlib.h 1.2.11) deflate() returned error -2 with z_stream->msg=="" Z_FINISH=4 Z_BLOCK=5. Please include the full output above and below this message in your data.table bug report.>
  Test 1658.43 ran without errors but failed check that x equals y:
  > x = fread(f1)
  Empty data.table (0 rows and 2 cols): a,b
   [Key= Types=log,log Classes=log,log]
  > y = DT
       a b [Key= Types=int,int Classes=int,int]
    1: 1 1
    2: 1 1
   ---
  199: 2 4
  200: 2 4
  Different number of rows
  Error in fwrite(DT, file = f3 <- tempfile(), compress = "gzip") :
    zlib 1.2.11 (zlib.h 1.2.11) deflate() returned error -2 with z_stream->msg=="" Z_FINISH=4 Z_BLOCK=5. Please retry fwrite() with verbose=TRUE and include the full output with your data.table bug report.
  Error in test.data.table() :
    Failed after test 1658.43 before the next test() call in /home/ripley/R/Lib32/data.table/tests/tests.Rraw.bz2
  Execution halted
checking for unstated dependencies in vignettes ... OK
checking package vignettes in ‘inst/doc’ ... OK
checking re-building of vignette outputs ... [139s/159s] OK
checking PDF version of manual ... OK
checking for detritus in the temp directory ... OK
DONE
Status: 1 ERROR
```

### PR DESCRIPTION
**Pull request by mattdowle**
Closes #4099 
Allocates the set of structs before the parallel region to avoid the move on Solaris
Adds the extra trace point mentioned in #4099, in case this theory is wrong
Will remove the word "should" in the news item after release, if it is successful.

### CODE REVIEW

File: src/fwrite.c [hunk 1]
```diff
@@ -906,19 +914,19 @@ void fwriteMain(fwriteMainArgs args)
       // compress buffer if gzip
       if (args.is_gzip && !failed) {
         myzbuffUsed = zbuffSize;
-        if (verbose) {DTPRINT(_("z_stream for data (%d): "), 2); print_z_stream(&mystream);}
-        int ret = compressbuff(&mystream, myzBuff, &myzbuffUsed, myBuff, (size_t)(ch-myBuff));
-        if (verbose) {DTPRINT(_("z_stream for data (%d): "), 3); print_z_stream(&mystream);}
+        if (verbose) {DTPRINT(_("z_stream for data (%d): "), 3); print_z_stream(mystream);}
```
Comment (MichaelChirico) [inline src/fwrite.c:917]: question: supposing this works, would you then aim to remove all the extra verbose printing for tracing in the next release? (less maintenance overhead / tidier code vs. ease of setting up the in-depth tracing should a similar error recur later on)

curious your thinking

Comment (mattdowle) [reply src/fwrite.c:917]: yes will just remove the extra tracing.  can always get it back from the history should we need it again
