### PR TITLE
Closes #3639 -- proper handling of CPLXSXP in dogroups

### LINKED ISSUE #3639: Wrong values in j with complex values if "by" has more than 1 group.
I understand that complex number support is not fully implemented (see [this](https://github.com/Rdatatable/data.table/issues/1444) issue), but this is weird and, very serious, IMHO, because it can be a big source of silent errors.  

``` r
library(data.table)
set.seed(42)
data <- setDT(expand.grid(x = 1:10,
                    a = c("a", "b"),
                    b = 1:2))
data[, z := rnorm(1:.N) + rnorm(1:.N)*1i]


data2 <- data[, .(x = x, z = z), by = .(a, b)]
```

Now both data.tables should have the same data, but…

``` r
rbind(data[a == "b" & b == 2 & x == 1],
      data2[a == "b" & b == 2 & x == 1], use.names = TRUE)
#>    x a b                    z
#> 1: 1 b 2 0.4554501-1.0431189i
#> 2: 1 b 2 0.6359504+0.2765507i
```

The problems are not evently distributed:

``` r
setnames(data2, "z", "z2")
merged <- data2[data, on = c("x", "a", "b")]

library(ggplot2)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
ggplot(merged, aes(x, abs(z - z2))) +
    geom_line() +
    facet_grid(a ~ b)
```

And it doesn’t happen if “by” has only one group

``` r
data2 <- data[, .(x = x, z = z), by = .(interaction(a, b, sep = "."))]


data[a == "b" & b == 2 & x == 1]$z == data2[interaction == "b.2" & x == 1]$z
#> [1] TRUE
```

<sup>Created on 2019-06-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

### PR DESCRIPTION
**Pull request by MichaelChirico**
#3639

Haven't quite figured out the ins and outs of `CPLXSXP` and `COMPLEX()` usage yet but I think this gets at the kernel of the issue -- `dogroups` assumes `SIZEOF` is either 4 or 8, not so for `CPLXSXP` (16). Will come back to this.

FWIW `grep -Er "==\s?4" src` only turns up `reorder` and `dogroups`, so I think this and #3688 should cover this class of issue.

### CODE REVIEW

File: src/dogroups.c [hunk 1]
```diff
@@ -382,14 +392,20 @@ SEXP dogroups(SEXP dt, SEXP dtcols, SEXP groups, SEXP grpcols, SEXP jiscols, SEX
...
-      } else {
+      } else if (tsize==8) {
         double *td = REAL(target);
         double *sd = REAL(source);
         for (int r=0; r<maxn; ++r) td[ansloc+r] = sd[igrp];
+      } else {
+        // #3634 -- CPLXSXP columns have size 16
+        double complex *td = (double complex *)COMPLEX(target);
+        double complex *sd = (double complex *)COMPLEX(source);
+        for (int r=0; r<maxn; ++r) td[ansloc+r] = sd[igrp];
```
Comment (MichaelChirico) [inline src/dogroups.c]: TBH I don't really know what this branch is doing so I don't know how to put in a test for it.

File: src/dogroups.c [hunk 2]
```diff
@@ -143,6 +145,11 @@ SEXP dogroups(SEXP dt, SEXP dtcols, SEXP groups, SEXP grpcols, SEXP jiscols, SEX
         case REALSXP :
           REAL(VECTOR_ELT(SDall,j))[0] = NA_REAL;
           break;
+        case CPLXSXP :
```
Comment (MichaelChirico) [inline src/dogroups.c]: I don't know what this `switch` is doing, but here's how to initialize `CPLXSXP` -- set the `.r` and `.i` components to `NA_REAL` (taken from `r-source/src/main/complex.c`)

File: src/dogroups.c [hunk 3]
```diff
@@ -382,14 +401,20 @@ SEXP dogroups(SEXP dt, SEXP dtcols, SEXP groups, SEXP grpcols, SEXP jiscols, SEX
...
         double *sd = REAL(source);
         for (int r=0; r<maxn; ++r) td[ansloc+r] = sd[igrp];
+      } else {
+        // #3634 -- CPLXSXP columns have size 16
+        double complex *td = (double complex *)COMPLEX(target);
+        double complex *sd = (double complex *)COMPLEX(source);
+        for (int r=0; r<maxn; ++r) td[ansloc+r] = sd[igrp];
       }
       // Shouldn't need SET_* to age objects here since groups, TO DO revisit.
     }
```
Comment (MichaelChirico) [inline src/dogroups.c]: There's one more `switch (TYPEOF(target))` just below here (also I don't know what it's doing), I couldn't figure out how to get that one to work though. Attempts:

```
case CPLXSXP : {
  double complex *td = (double complex *)(COMPLEX(target) + thisansloc);
  // attempt 1; fails because double complex doesn't have .r/.i, only CPLXSXP does
  for (int r=0; r<maxn; ++r) { td[r].r = NA_REAL; td[r].i = NA_REAL; }
  // attempt 2; fails because i'm not allowed to assign to RHS of creal()/cimag()
  for (int r=0; r<,maxn; ++r) { creal(td[r]) = NA_REAL; cimag(td[r]) = NA_REAL; }
} break;
```

**Comment by MichaelChirico** [comment]
The code is working, just need to improve coverage (any ideas?)

File: src/dogroups.c [hunk 4]
```diff
@@ -415,6 +446,11 @@ SEXP dogroups(SEXP dt, SEXP dtcols, SEXP groups, SEXP grpcols, SEXP jiscols, SEX
           double *td = REAL(target)+thisansloc;
           for (int r=0; r<maxn; ++r) td[r] = NA_REAL;
         } break;
+        case CPLXSXP : {
+        double complex *td = (double complex *)(COMPLEX(target) + thisansloc);
+        for (int r=0; r<maxn; ++r) { td[r] = NA_REAL + NA_REAL*I; }
```
Comment (MichaelChirico) [inline src/dogroups.c]: again, no idea what this branch is really doing so I haven't confirmed it works, but at least it compiles

File: src/dogroups.c [hunk 5]
```diff
@@ -382,14 +401,20 @@ SEXP dogroups(SEXP dt, SEXP dtcols, SEXP groups, SEXP grpcols, SEXP jiscols, SEX
...
+      if (tsize==4) {
         int *td = INTEGER(target);
         int *sd = INTEGER(source);
         for (int r=0; r<maxn; ++r) td[ansloc+r] = sd[igrp];
-      } else {
+      } else if (tsize==8) {
         double *td = REAL(target);
         double *sd = REAL(source);
         for (int r=0; r<maxn; ++r) td[ansloc+r] = sd[igrp];
+      } else {
```
Comment (MichaelChirico) [inline src/dogroups.c]: this one is in the `ngrpcols` loop, so covering it requires being able to group `by` complex, which we can't (yet)

File: src/dogroups.c [hunk 6]
```diff
@@ -167,6 +174,10 @@ SEXP dogroups(SEXP dt, SEXP dtcols, SEXP groups, SEXP grpcols, SEXP jiscols, SEX
         case REALSXP :
           REAL(VECTOR_ELT(xSD,j))[0] = NA_REAL;
           break;
+        case CPLXSXP :
+          COMPLEX(VECTOR_ELT(xSD, j))[0].r = NA_REAL;
+          COMPLEX(VECTOR_ELT(xSD, j))[0].i = NA_REAL;
+          break;
```
Comment (MichaelChirico) [inline src/dogroups.c]: IIUC this is coming from a join, so we won't be able to cover it yet.

Minimal example to trigger the `INTSXP` branch of this `switch` (adapted test 1283.3):

```
dt1 <- data.table(a=rep(1:2, each=2), c=c(7L, 2L, 4L, 8L))
dt2 <- data.table(b=rep(2:3), c=c(2L, 6L), d=c(20L, 8L))
dt1[dt2, on = c(a = 'b'), .(a=a), by=.EACHI]
```

I believe it's because `j` uses a column from the LHS of `on`.

But joins aren't available for complex yet...

**Comment by MichaelChirico** [comment]
OK. The remaining codecov problems I think are outside the scope of this PR (see comments). does it make sense to just delete that part of the patch and save it for when it's actually testable?

Will also file a coverage commit for `dogroups`

File: inst/tests/tests.Rraw [hunk 7]
```diff
@@ -7326,6 +7326,16 @@ test(1540.35, DT1[DT3, lapply(.SD, function(x) x * mul),
...
+## more coverage tests for by = .EACHI, on = c(LHS = 'RHS') for numeric type
+set.seed(45L)
+DT1 = data.table(x=sample(letters[1:3], 15, TRUE), y=sample(6:10, 15, TRUE),
+                 a=sample(100, 15), b=runif(15))
+DT2 = CJ(x=letters[1:3], y=6:10)[, mul := sample(20, 15)][sample(15L, 5L)]
+DT3 = rbindlist(list(DT2, list(x="d", y=7L, mul=100L)))
+DT3 = DT3[sample(nrow(DT3))]
+DT1[ , x_num := match(x, letters) + .1]
+DT3[ , x_num := match(x, letters) + .1]
+test(1540.36, DT1[DT3, .(x_num), by=.EACHI, on=c(x_num="x_num")])
```
Comment (MichaelChirico) [inline inst/tests/tests.Rraw]: strangely enough, I couldn't get this test to hit the `LGLSXP` branch:

```
DT1[ , x_lgl := x > = 'a']
DT3[ , x_lgl := x > 'a']
DT1[DT3, .(x_lgl), by=.EACHI, on=c(x_lgl="x_lgl")]
```

doesn't do it...

File: src/dogroups.c [hunk 8]
```diff
@@ -167,20 +174,24 @@ SEXP dogroups(SEXP dt, SEXP dtcols, SEXP groups, SEXP grpcols, SEXP jiscols, SEX
...
         case STRSXP :
           SET_STRING_ELT(VECTOR_ELT(xSD,j),0,NA_STRING);
           break;
         case VECSXP :
           SET_VECTOR_ELT(VECTOR_ELT(xSD,j),0,R_NilValue);
           break;
```
Comment (MichaelChirico) [inline src/dogroups.c]: Should we nocov this branch (or set it to error even?)

IIUC hitting this branch would require first joining on `VECSXP` column in `on`, I don't think we have any plan to support list-to-list joins?

File: src/assign.c [hunk 9]
```diff
@@ -1002,6 +1011,11 @@ void writeNA(SEXP v, const int from, const int n)
       for (int i=from; i<=to; ++i) vd[i] = NA_REAL;
     }
   } break;
+  case CPLXSXP: {
+    Rcomplex *vd = COMPLEX(v);
+    Rcomplex NA_CPLX = {NA_REAL, NA_REAL};
```
Comment (MichaelChirico) [inline src/assign.c]: a bit strange why we have to define this ourselves but I see it done like this in a few places in `r-source` (e.g. `subset.c`)

**Comment by mattdowle** [comment]
Have we heard from many users requesting complex support?
I'll try and get through these PRs asap, and hopefully they are quick, but it's adding complexity (pun intended) when another approach could be just to not support complex yet until other higher value things are done first.
If the idea is to pick off something where you can learn the code base, that's a good idea, and I'm ok to merge them in on that basis.  Just hoping these 6 PRs are quick and they don't cause unintended effects.

Some links to users and fields requesting complex support please, would keep me happy that it's worth doing.

File: src/dogroups.c (hunk 8 above)
Comment (mattdowle) [reply src/dogroups.c]: don't no cov it.  I'd say don't error either because something somewhere might be using it.  I'd say just leave it as-is for now until it can be covered at a later date.

File: src/assign.c (hunk 9 above)
Comment (mattdowle) [reply src/assign.c]: Yes I see 3 in src/main/subset.c too.  Those are the only occurence of "NA_C" in the entire source tree of R.  So since it's so rarely used, I guess it just hasn't been looked at.  Which seems reasonable.

**Comment by eliocamp** [comment]
I'm one happy data.table user that uses complex numbers frequently and would be even happier if complex support is enhanced :smile:. Perusing github I see there are some issues addressing it:

* https://github.com/Rdatatable/data.table/issues/33

* https://github.com/Rdatatable/data.table/issues/256

* https://github.com/Rdatatable/data.table/issues/602

 * https://github.com/Rdatatable/data.table/issues/982

* https://github.com/Rdatatable/data.table/issues/1444

* https://github.com/Rdatatable/data.table/issues/3639

Not a lot (understandably), but non-zero.

**Comment by mattdowle** [comment]
@eliocamp Great, thanks. I looked through them. It looks to me as if it's programmers checking that all types are supported for completeness reasons, rather than users in the real-world actually needing complex number support.   I did find one field mentioned in those issues : 
* signal processing, especially for the analysis of power spectra.

What's your field that you use complex numbers in?

**Comment by eliocamp** [comment]
Meteorology, but I use some signal processing methods to analyse fields. Complex Principal Component Analysis, for example.

**Comment by mattdowle** [comment]
Good to know! Are there any articles that show how meteorology, signal processing and/or complex-PCA need complex numbers in the context of data.table-like operations like grouping? I did complex number theory in undergraduate applied math and much enjoyed it, but I've never used complex numbers since then.

**Comment by mattdowle** [comment]
All looks good. I realize the diff coverage is under target but that's ok, because as Michael wrote, other PRs will cover those in future.

**Comment by MichaelChirico** [comment]
> pick off something where you can learn the code base

in fact that's the main thinking. I imagine there are some use cases around Fourier series running around but yea, I haven't come across it myself in a while either

File: src/subset.c [hunk 10]
```diff
@@ -77,7 +77,6 @@ static void subsetVectorRaw(SEXP ans, SEXP source, SEXP idx, const bool anyNA)
   case CPLXSXP : {
     Rcomplex *sp = COMPLEX(source);
     Rcomplex *ap = COMPLEX(ans);
-    Rcomplex NA_CPLX = { NA_REAL, NA_REAL };
```
Comment (MichaelChirico) [inline src/subset.c]: looking at it again, would just inlining `= (Rcomplex){NA_REAL, NA_REAL}` do the trick?

Comment (mattdowle) [reply src/subset.c]: I don't think `(Rcomplex){NA_REAL, NA_REAL}` will work. Because `Rcomplex` is a `struct`. The {NA_REAL, NA_REAL} is special syntax just for initialization of a variable/struct.

**Comment by eliocamp** [comment]
> Good to know! Are there any articles that show how meteorology, signal processing and/or complex-PCA need complex numbers in the context of data.table-like operations like grouping? I did complex number theory in undergraduate applied math and much enjoyed it, but I've never used complex numbers since then.

I've never read anything specific about data.table. Here's a paper about the method: https://journals.ametsoc.org/doi/abs/10.1175/1520-0450%281984%29023%3C1660%3ACPCATA%3E2.0.CO%3B2

This is the code I'm using now. It gets the Hilbert transform of the data and then does an EOF (Empirical Orthogonal Functions --what we meteorologists call PCA) for each season, dataset and height level. Because of #3639 I had to use the workaround of separating the real an imaginary parts and then joining them together after the grouping was done. 

```r
ceof <-  data %>%
  .[, c("R", "I") := ReIm(spectral::analyticFunction(hgt.minus)),
    by = .(lat, season, year, dataset, lev)] %>% 
  .[, {
    d <- copy(.SD)[, hgt := R + I*1i]
    list(ceof = list(
      EOF(hgt ~ year | lon + lat, n = 1:2, 
          B = 5000, suffix = "cPC", data = d)
    ))
  }, by = .(dataset, season, lev)]
```
`EOF()` (a function I created and available in the metR package) returns a list of data.tables that are the matrices of the Singular Value Decomposition in "long" format. So `ceof` is a data.table with a column names "ceof" (yeah, not very smart naming convention) that that holds said list of data.tables, one for each combination of dataset, season and height level.

**Comment by mattdowle** [comment]
Thanks @eliocamp, helps a lot!  Continuing here: https://github.com/Rdatatable/data.table/pull/3701#issuecomment-512605868
