### PR TITLE
gshift() of one column returns a vector, not list(vector)

### LINKED ISSUE #5939: `x[, .(shift(b)), keyby = a]` returns list type (should be int)
Upgrading to the latest CRAN version of data.table, expression like `x[, .(shift(b)), keyby = a]` will return a list type for `V1` column, which is unexpected and inconsistent. In previous versions, it always returns `<int>`.

``` r
library(data.table)
x = data.table(a = c(rep(1, 5), rep(2, 5)), b = 1:10)
x[, shift(b), keyby = a]
#> Key: <a>
#>         a    V1
#>     <num> <int>
#>  1:     1    NA
#>  2:     1     1
#>  3:     1     2
#>  4:     1     3
#>  5:     1     4
#>  6:     2    NA
#>  7:     2     6
#>  8:     2     7
#>  9:     2     8
#> 10:     2     9
x[, .(shift(b)), keyby = a]
#> Key: <a>
#>         a     V1
#>     <num> <list> <------------ ### it should be <int> ###
#>  1:     1     NA
#>  2:     1      1
#>  3:     1      2
#>  4:     1      3
#>  5:     1      4
#>  6:     2     NA
#>  7:     2      6
#>  8:     2      7
#>  9:     2      8
#> 10:     2      9
x[, .(shift(b), b), keyby = a]
#> Key: <a>
#>         a    V1     b
#>     <num> <int> <int>
#>  1:     1    NA     1
#>  2:     1     1     2
#>  3:     1     2     3
#>  4:     1     3     4
#>  5:     1     4     5
#>  6:     2    NA     6
#>  7:     2     6     7
#>  8:     2     7     8
#>  9:     2     8     9
#> 10:     2     9    10
```

<sup>Created on 2024-02-18 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.3.2 (2023-10-31)
#>  os       macOS Sonoma 14.0
#>  system   aarch64, darwin20
#>  ui       X11
#>  language en
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Asia/Shanghai
#>  date     2024-02-18
#>  pandoc   3.1.1 @ /Applications/RStudio.app/Contents/Resources/app/quarto/bin/tools/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date (UTC) lib source
#>  cli           3.6.1   2023-03-23 [1] CRAN (R 4.3.0)
#>  data.table  * 1.15.0  2024-01-30 [1] CRAN (R 4.3.1)
#>  digest        0.6.33  2023-07-07 [1] CRAN (R 4.3.0)
#>  evaluate      0.21    2023-05-05 [1] CRAN (R 4.3.0)
#>  fastmap       1.1.1   2023-02-24 [1] CRAN (R 4.3.0)
#>  fs            1.6.3   2023-07-20 [1] CRAN (R 4.3.0)
#>  glue          1.6.2   2022-02-24 [1] CRAN (R 4.3.0)
#>  htmltools     0.5.6   2023-08-10 [1] CRAN (R 4.3.0)
#>  knitr         1.44    2023-09-11 [1] CRAN (R 4.3.0)
#>  lifecycle     1.0.3   2022-10-07 [1] CRAN (R 4.3.0)
#>  magrittr      2.0.3   2022-03-30 [1] CRAN (R 4.3.0)
#>  purrr         1.0.2   2023-08-10 [1] CRAN (R 4.3.0)
#>  R.cache       0.16.0  2022-07-21 [1] CRAN (R 4.3.0)
#>  R.methodsS3   1.8.2   2022-06-13 [1] CRAN (R 4.3.0)
#>  R.oo          1.25.0  2022-06-12 [1] CRAN (R 4.3.0)
#>  R.utils       2.12.2  2022-11-11 [1] CRAN (R 4.3.0)
#>  reprex        2.0.2   2022-08-17 [1] CRAN (R 4.3.0)
#>  rlang         1.1.1   2023-04-28 [1] CRAN (R 4.3.0)
#>  rmarkdown     2.24    2023-08-14 [1] CRAN (R 4.3.0)
#>  rstudioapi    0.15.0  2023-07-07 [1] CRAN (R 4.3.0)
#>  sessioninfo   1.2.2   2021-12-06 [1] CRAN (R 4.3.0)
#>  styler        1.10.2  2023-08-29 [1] CRAN (R 4.3.0)
#>  vctrs         0.6.3   2023-06-14 [1] CRAN (R 4.3.0)
#>  withr         2.5.0   2022-03-03 [1] CRAN (R 4.3.0)
#>  xfun          0.40    2023-08-09 [1] CRAN (R 4.3.0)
#>  yaml          2.3.7   2023-01-23 [1] CRAN (R 4.3.0)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #5939 

No NEWS since the NEWS item belongs in the patch branch.

### CODE REVIEW

File: src/gsumm.c [hunk 1]
```diff
@@ -1268,6 +1268,7 @@ SEXP gshift(SEXP x, SEXP nArg, SEXP fillArg, SEXP typeArg) {
     copyMostAttrib(x, tmp); // needed for integer64 because without not the correct class of int64 is assigned
   }
   UNPROTECT(nprotect);
-  return(ans);
+  // consistency with plain shift(): "strip" the list in the 1-input case, for convenience
+  return isVectorAtomic(x) && length(ans) == 1 ? VECTOR_ELT(ans, 0) : ans;
```
Comment (MichaelChirico) [inline src/gsumm.c:1272]: @ben-schwen do we actually need the `isVectorAtomic()` check in the `gshift` case? Is it possible to get a `list()` here in gshift?

Comment (ben-schwen) [reply src/gsumm.c:1272]: Right now no, the only supported types are the six atomic vector types. AFAIR I deactivated the support for list columns because we use `coerceAs` for the fill argument and `coerceAs` only supports atomic vectors.

**Comment by renkun-ken** [comment]
```
remotes::install_github("Rdatatable/data.table#5950")
library(data.table)

dt <- expand.grid(
  date = 1:10,
  time = 1:10,
  id = 1:5
)

setDT(dt, key = c("date", "time", "id"))
dt[, x := runif(.N)]
dt[time == 1, x1 := shift(x, type = "lead"), by = id]
```

```
Key: <date, time, id>
Index: <time>
      date  time    id         x                                                              x1
     <int> <int> <int>     <num>                                                          <list>
  1:     1     1     1 0.3991771 0.1244421,0.6010204,0.7708546,0.4181234,0.6126064,0.6068231,...
  2:     1     1     2 0.1191543 0.1244421,0.6010204,0.7708546,0.4181234,0.6126064,0.6068231,...
  3:     1     1     3 0.8993754 0.1244421,0.6010204,0.7708546,0.4181234,0.6126064,0.6068231,...
  4:     1     1     4 0.1927022 0.1244421,0.6010204,0.7708546,0.4181234,0.6126064,0.6068231,...
  5:     1     1     5 0.9353783 0.1244421,0.6010204,0.7708546,0.4181234,0.6126064,0.6068231,...
 ---                                                                                            
496:    10    10     1 0.8060775                                                          [NULL]
497:    10    10     2 0.8797189                                                          [NULL]
498:    10    10     3 0.8200970                                                          [NULL]
499:    10    10     4 0.3559045                                                          [NULL]
500:    10    10     5 0.1516604                                                          [NULL]
```

still not desired result.

**Comment by ben-schwen** [comment]
Apparently, gshift cannot work with subsetting since it always creates vectors of `length(x)` but not length `irows`.

**Comment by ben-schwen** [comment]
Sorry for hijacking the PR, but it should go into patch release and was also #5939

**Comment by MichaelChirico** [comment]
thanks; since this PR targets master let's leave the NEWS out. I'll add the NEWS to the copycat PR targeting the patch release. Or maybe we should target the patch instead 🤔

**Comment by jangorecki** [comment]
Whichever one we target, we just cherry pick the other one.

**Comment by renkun-ken** [comment]
The latest commit works for me now. Thanks!

**Comment by MichaelChirico** [comment]
> Sorry for hijacking the PR, but it should go into patch release and was also #5939

I think we actually have two distinct bugs on our hands, so I will cherry-pick your fix into a separate PR.

File: src/gsumm.c (hunk 1 above)
Comment (MichaelChirico) [reply src/gsumm.c:1272]: I'll leave the `isVectorAtomic()` check, simpler to keep consistency with "plain" shift.

**Comment by MichaelChirico** [comment]
@ben-schwen / @jangorecki any final review here? running up against our CRAN deadline

**Comment by ben-schwen** [comment]
LGTM
