### PR TITLE
Fix up some potential memory leaks in fwrite

### LINKED ISSUE #6733: Memory leak in `fwrite`
Found while testing the fix for #6731.

Setting aside the leaks from `zlib` and `fontconfig`, we've got the following for `tests/main.R`:

```
Direct leak of 125829120 byte(s) in 15 object(s) allocated from:
    #1 0x7f43e5ea224a in fwriteMain src/fwrite.c:792
    #2 0x7f43e5ea7638 in fwriteR src/fwriteR.c:310
```

plus a few tens of megabytes from other objects allocated in the same place.

Looks like this allocation:
https://github.com/Rdatatable/data.table/blob/1aa92bc4ab3206b5e9f8accdc5b205edbb76c73a/src/fwrite.c#L792
are not always matched with this deallocation:
https://github.com/Rdatatable/data.table/blob/1aa92bc4ab3206b5e9f8accdc5b205edbb76c73a/src/fwrite.c#L1096

(Some allocations done internally by `zlib` are also leaks, but LeakSanitizer doesn't trace them to a specific line in `data.table`.)

We've got quite a few calls to `STOP()` between the two lines, and most of those don't release the memory allocated for `buffPool`. This bisects to e0abdfcd79ba30efcf679e33cbb8eba897a46f9c, i.e., #6393. Before this commit, `tests/main.R` finishes without any notes from LeakSanitizer.

**Edit**: the title used to say "leak in `fread`", which was not correct at all.

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #6733.

Looked for any `STOP` or `return` before `free()` is called on any `malloc()` object, and made sure to `free()` before those exits if not already done & that object has successfully `malloc()`'d.

Also

 - Moved the `#ifndef` guards for `NOZLIB` outside the `args.is_gzip` checks, so that gzip-disabled installations don't even bother checking `is_gzip` (we error if `is_gzip` is attempted in gzip-disabled installations above)
 - Moved some `DTPRINT()` calls alerting about allocations to _after_ we checked that the allocation succeeded (the error message is informative enough in case of failure)
 
Thanks @aitap for pointing out the `mystream` issue too. cc @philippechataignon.

### CODE REVIEW

File: src/fwrite.c [hunk 1]
```diff
@@ -829,14 +820,18 @@ void fwriteMain(fwriteMainArgs args)
       DTPRINT(_("Allocate %zu bytes (%zu MiB) for zbuffPool\n"), alloc_size, alloc_size / MEGA);
     }
     zbuffPool = malloc(alloc_size);
-    if (!zbuffPool) {
+    if (zbuffPool == NULL) {
```
Comment (MichaelChirico) [inline src/fwrite.c:823]: We use this throughout the codebase and our "linter" checks for `!` usage specifically:

https://github.com/Rdatatable/data.table/blob/f72e46bbedc3f3f8c2abe0ea779d80e1e034ce32/.ci/linters/c/alloc_linter.R#L23

```suggestion
    if (!zbuffPool) {
```

**Comment by philippechataignon** [comment]
A lot of allocation stuff in fwrite was written by Matt. I remove allocation for zlib streams and declare them as z_stream, not z_stream*. I've had an malloc(0) for freeing zbuffPool in all case (except if NOZLIB is defined).

File: src/fwrite.c (hunk 1 above)
Comment (philippechataignon) [reply src/fwrite.c]: OK, sorry for this useless change.

File: src/fwrite.c [hunk 2]
```diff
@@ -836,7 +827,11 @@ void fwriteMain(fwriteMainArgs args)
            zbuffSize / MEGA, nth, errno, strerror(errno));
       // # nocov end
     }
+  } else {
+    // if no is_gzip, malloc 0 for allowing freeing zbuffPool
+    zbuffPool = malloc(0);
```
Comment (aitap) [inline src/fwrite.c:833]: The C standard (even C89) allows giving null pointers to `free` (and allows `malloc(0)` to return a null pointer). Circa-2016 (R-3.3.0 release year) C standard libraries should all handle `free(NULL)` without a problem.

Initialising `char * zbuffPool = NULL` on line 801 above and skipping the `else` branch here would have been sufficient.

File: src/fwrite.c [hunk 3]
```diff
@@ -1067,36 +1073,29 @@ void fwriteMain(fwriteMainArgs args)
...
+  if (args.is_gzip) {
+    unsigned char tail[10];
+    tail[0] = 3;
+    tail[1] = 0;
+    PUT4(tail + 2, crc);
+    PUT4(tail + 6, len);
+    int ret = WRITE(f, tail, 10);
+    compress_len += 10;
+    if (ret == -1)
+      STOP("Error: can't write gzip tailer"); // # nocov
```
Comment (aitap) [inline src/fwrite.c:1098]:
```suggestion
      STOP("Error: can't write gzip trailer"); // # nocov
```
Does this message need translation like other calls to `STOP(...)`?

**Review by aitap — COMMENTED** [review]
Thank you! We needed those `deflateEnd`s in addition to the `free`s. One remaining leak was visible through testing (zero-row `fwrite`) and one more leak on the error path is not easily testable but was confirmed manually in the debugger. There are no remaining complaints from LeakSanitizer.

File: src/fwrite.c (hunk 3 above)
Comment (MichaelChirico) [reply src/fwrite.c:1098]: I thought 'tailer' was a special word 😂 

Yes, added `_()`

File: src/fwrite.c (hunk 1 above)
Comment (MichaelChirico) [reply src/fwrite.c]: NP, it's of course equivalent, just a matter of style (and some guides recommend your approach as being more transparent). Only using `!` for consistency.
