### PR TITLE
coerceFill puts Inf to NA_INTEGER for integer

### LINKED ISSUE #3929: clang UBSAN error on nafill
I ran through gcc UBSAN in release procedures, including all `*.Rraw` tests which passed fine.  So it appears to be clang only.

https://www.stats.ox.ac.uk/pub/bdr/memtests/clang-UBSAN/data.table/tests/
```

R Under development (unstable) (2019-10-03 r77254) -- "Unsuffered Consequences"
Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> require(data.table)
Loading required package: data.table
> test.data.table(script="nafill.Rraw")
getDTthreads(verbose=TRUE):
  omp_get_num_procs()            24
  R_DATATABLE_NUM_PROCS_PERCENT  unset (default 50)
  R_DATATABLE_NUM_THREADS        unset
  omp_get_thread_limit()         2
  omp_get_max_threads()          24
  OMP_THREAD_LIMIT               2
  OMP_NUM_THREADS                unset
  RestoreAfterFork               true
  data.table is using 2 threads. See ?setDTthreads.
test.data.table() running: /data/gannet/ripley/R/packages/tests-clang-SAN/data.table.Rcheck/data.table/tests/nafill.Rraw 

Running test id 1.01      
Running test id 1.02      
...
Running test id 6.45      
Running test id 6.46      utils.c:163:51: runtime error: -inf is outside the range of representable values of type 'int'
    #0 0x7fe0f8b09e65 in coerceFill /data/gannet/ripley/R/packages/tests-clang-SAN/data.table/src/utils.c:163:51
    #1 0x7fe0f8b0a0c2 in coerceFillR /data/gannet/ripley/R/packages/tests-clang-SAN/data.table/src/utils.c:179:3
    #2 0x86d8f9 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7343:21
    #3 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #4 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #5 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #6 0x855ab8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743:12
    #7 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #8 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #9 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #10 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #11 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #12 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #13 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #14 0x855ab8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743:12
    #15 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #16 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #17 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #18 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #19 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #20 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #21 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #22 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #23 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #24 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #25 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #26 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #27 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #28 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #29 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #30 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #31 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #32 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #33 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #34 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #35 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #36 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #37 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #38 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #39 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #40 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #41 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #42 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #43 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #44 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #45 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #46 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #47 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #48 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #49 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #50 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #51 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #52 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #53 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #54 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #55 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #56 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #57 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #58 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #59 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #60 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #61 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #62 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #63 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #64 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #65 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #66 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #67 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #68 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #69 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #70 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #71 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #72 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #73 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #74 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #75 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #76 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #77 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #78 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #79 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #80 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #81 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #82 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #83 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #84 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #85 0x855ab8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743:12
    #86 0x8bd81c in do_begin /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:2391:10
    #87 0x85537b in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:695:12
    #88 0x85537b in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:695:12
    #89 0x8c5e2a in do_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:3231:9
    #90 0x8710a5 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6796:14
    #91 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #92 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #93 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #94 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #95 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #96 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #97 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #98 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #99 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #100 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #101 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #102 0x855ab8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743:12
    #103 0x98b296 in Rf_ReplIteration /data/gannet/ripley/R/svn/R-devel/src/main/main.c:260:2
    #104 0x98f7b0 in R_ReplConsole /data/gannet/ripley/R/svn/R-devel/src/main/main.c:310:11
    #105 0x98f595 in run_Rmainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1108:5
    #106 0x4da35a in main /data/gannet/ripley/R/svn/R-devel/src/main/Rmain.c:29:5
    #107 0x7fe109755f42 in __libc_start_main (/lib64/libc.so.6+0x23f42)
    #108 0x43036d in _start (/data/gannet/ripley/R/R-clang-SAN/bin/exec/R+0x43036d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior utils.c:163:51 in 
utils.c:165:55: runtime error: -inf is outside the range of representable values of type 'long'
    #0 0x7fe0f8b09ea1 in coerceFill /data/gannet/ripley/R/packages/tests-clang-SAN/data.table/src/utils.c:165:55
    #1 0x7fe0f8b0a0c2 in coerceFillR /data/gannet/ripley/R/packages/tests-clang-SAN/data.table/src/utils.c:179:3
    #2 0x86d8f9 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:7343:21
    #3 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #4 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #5 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #6 0x855ab8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743:12
    #7 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #8 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #9 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #10 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #11 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #12 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #13 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #14 0x855ab8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743:12
    #15 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #16 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #17 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #18 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #19 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #20 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #21 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #22 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #23 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #24 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #25 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #26 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #27 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #28 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #29 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #30 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #31 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #32 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #33 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #34 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #35 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #36 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #37 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #38 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #39 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #40 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #41 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #42 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #43 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #44 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #45 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #46 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #47 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #48 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #49 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #50 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #51 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #52 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #53 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #54 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #55 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #56 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #57 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #58 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #59 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #60 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #61 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #62 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #63 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #64 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #65 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #66 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #67 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #68 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #69 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #70 0x8acb7d in forcePromise /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:516:8
    #71 0x8e342f in FORCE_PROMISE /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4928:15
    #72 0x8e342f in getvar /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:4994:14
    #73 0x87d826 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6548:20
    #74 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #75 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #76 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #77 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #78 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #79 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #80 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #81 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #82 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #83 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #84 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #85 0x855ab8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743:12
    #86 0x8bd81c in do_begin /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:2391:10
    #87 0x85537b in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:695:12
    #88 0x85537b in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:695:12
    #89 0x8c5e2a in do_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:3231:9
    #90 0x8710a5 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6796:14
    #91 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #92 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #93 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #94 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #95 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #96 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #97 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #98 0x873771 in bcEval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:6764:12
    #99 0x854bb8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:620:8
    #100 0x8b25bb in R_execClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c
    #101 0x8af895 in Rf_applyClosure /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:1706:16
    #102 0x855ab8 in Rf_eval /data/gannet/ripley/R/svn/R-devel/src/main/eval.c:743:12
    #103 0x98b296 in Rf_ReplIteration /data/gannet/ripley/R/svn/R-devel/src/main/main.c:260:2
    #104 0x98f7b0 in R_ReplConsole /data/gannet/ripley/R/svn/R-devel/src/main/main.c:310:11
    #105 0x98f595 in run_Rmainloop /data/gannet/ripley/R/svn/R-devel/src/main/main.c:1108:5
    #106 0x4da35a in main /data/gannet/ripley/R/svn/R-devel/src/main/Rmain.c:29:5
    #107 0x7fe109755f42 in __libc_start_main (/lib64/libc.so.6+0x23f42)
    #108 0x43036d in _start (/data/gannet/ripley/R/R-clang-SAN/bin/exec/R+0x43036d)

SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior utils.c:165:55 in 

10 longest running tests took 1s (29% of 4s)
    ID  time nTest
 1:  6 1.008    16
 2:  4 0.225    24
 3:  2 0.112     8
 4:  5 0.044     4
 5:  3 0.040     7
 6:  7 0.000     0
 7:  8 0.000     0
 8:  9 0.000     0
 9: 10 0.000     0
10: 11 0.000     0
endian==little, sizeof(long double)==16, sizeof(pointer)==8, TZ=Europe/London, locale='LC_CTYPE=en_GB.utf8;LC_NUMERIC=C;LC_TIME=en_GB.UTF-8;LC_COLLATE=C;LC_MONETARY=en_GB.UTF-8;LC_MESSAGES=en_GB.UTF-8;LC_PAPER=en_GB.UTF-8;LC_NAME=C;LC_ADDRESS=C;LC_TELEPHONE=C;LC_MEASUREMENT=en_GB.UTF-8;LC_IDENTIFICATION=C', l10n_info()='MBCS=TRUE; UTF-8=TRUE; Latin-1=FALSE', getDTthreads()='omp_get_num_procs()==24; R_DATATABLE_NUM_PROCS_PERCENT==unset (default 50); R_DATATABLE_NUM_THREADS==unset; omp_get_thread_limit()==2; omp_get_max_threads()==24; OMP_THREAD_LIMIT==2; OMP_NUM_THREADS==unset; RestoreAfterFork==true; data.table is using 2 threads. See ?setDTthreads.'

All 112 tests in tests/nafill.Rraw completed ok in 4.841s elapsed (4.906s cpu) on Thu Oct  3 13:07:58 2019
> 
> proc.time()
   user  system elapsed 
  6.331   0.358   6.387 
```

### PR DESCRIPTION
**Pull request by MichaelChirico**
Closes #3929

FWIW I am also not reproducing the UBSAN error on `gcc`. But the message in the CRAN failure is clear & can see why it would happen in the code there.

### CODE REVIEW

File: src/utils.c [hunk 1]
```diff
@@ -160,7 +160,7 @@ void coerceFill(SEXP fill, double *dfill, int32_t *ifill, int64_t *i64fill) {
         // NA -> NA, NaN -> NaN
         ifill[0] = NA_INTEGER; dfill[0] = rfill; i64fill[0] = NA_INTEGER64;
       } else {
-        ifill[0] = rfill>INT32_MAX ? NA_INTEGER : (int32_t)(rfill);
+        ifill[0] = rfill>INT32_MAX || !R_finite(rfill) ? NA_INTEGER : (int32_t)(rfill);
```
Comment (jangorecki) [inline src/utils.c]: I think we used capital case R_FINITE, should be fine to use it here too, you can grep for both and double check

Comment (mattdowle) [reply src/utils.c]: I didn't know `R_finite` was available actually. It seems to compile ok by the looks of it.   R 2.6.0 news contains this :
image
However, section 6.4 of R-exts points to the macro form (capitals) : 
https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Missing-and-IEEE-values
I can't see any mention of `R_finite` in R-exts, only `R_FINITE`.  So that's the reason to use `R_FINITE`. Also R_FINITE should be tested first in the `||` to use the short-circuit and avoid doubt over `rfill>INT32_MAX` on non-finite values.

Comment (mattdowle) [reply src/utils.c]: What about `<= INT32_MIN` ?     ( `<=` rather than `<` due to NA_INTEGER )

Comment (mattdowle) [reply src/utils.c]: Is `<=INT_MIN` needed on line 153 too?  https://github.com/Rdatatable/data.table/pull/3930/files#diff-74710e3ecbe94109f39de34133e1c8caR153

File: src/utils.c [hunk 2]
```diff
@@ -160,7 +160,7 @@ void coerceFill(SEXP fill, double *dfill, int32_t *ifill, int64_t *i64fill) {
...
         dfill[0] = rfill;
         i64fill[0] = rfill>INT64_MAX ? NA_INTEGER64 : (int64_t)(rfill);
```
Comment (mattdowle) [inline src/utils.c]: This line needed as well. Both 163 and 165 are flagged on CRAN.  Will do.
