### PR TITLE
Fix fread segfault from faulty assumption on compilers

### LINKED ISSUE #7183: ASAN error in fread.c
Here are the logs of the error:

https://gitlab.com/Rdatatable/data.table/-/jobs/10696837289

I think we should fix the bug (presumably introduced by #7138) before continuing to dig a hole with further edits to the file.

_Originally posted by @MichaelChirico in https://github.com/Rdatatable/data.table/issues/7181#issuecomment-3079228687_

### PR DESCRIPTION
**Pull request by badasahog**
Closed #7183 cc @MichaelChirico

### CODE REVIEW

**Comment by MichaelChirico** [comment]
thanks! would you mind

(1) adding a helpful comment for any intrepid future devs that have the same thoughts about making it const
(2) re-read the older PR again with fresh eyes, if memory serves this type of change was made more than once [it could just mean the other instances are not covered by tests & this not showing up]

File: src/fread.c [hunk 1]
```diff
@@ -927,10 +927,13 @@ static void parse_double_hexadecimal(FieldParseContext *ctx)
   if (neg) ch++;
   else if (*ch == '+') ch++;
 
-  const bool subnormal = ch[2] == '0';
+  bool subnormal = false;
 
+  // Important!
+  // Keep in mind that only ch[0] is guaranteed to be mapped.
+  // Rearanging these checks will lead to segfaults in rare cases.
```
Comment (MichaelChirico) [inline src/fread.c]:
```suggestion
  // Rearranging these checks (e.g. to make 'subnormal' const) will lead to segfaults in rare cases.
```

**Comment by MichaelChirico** [comment]
I believe these are also at risk:

https://github.com/Rdatatable/data.table/blob/c8bbb580dd5f54710583a3477382e949d093b302/src/fread.c#L775
https://github.com/Rdatatable/data.table/blob/c8bbb580dd5f54710583a3477382e949d093b302/src/fread.c#L946

Can you think of an input file that would trigger the segfault? If so we should add them as regression tests.

**Comment by badasahog** [comment]
Those wouldn't create a problem because ch[1] is tested first anyway (I'm not rearranging the order of access as far as I can tell)

**Comment by MichaelChirico** [comment]
Oh, got it, `ch[0]` is already implicitly tested before in both cases:

https://github.com/Rdatatable/data.table/blob/c8bbb580dd5f54710583a3477382e949d093b302/src/fread.c#L772

https://github.com/Rdatatable/data.table/blob/c8bbb580dd5f54710583a3477382e949d093b302/src/fread.c#L932

**Comment by MichaelChirico** [comment]
I suppose we could retain the `const` label by adding a layer of nesting:

```c
if (ch[0] == '0' && (ch[1] == 'x' || ch[1] == 'X')) {
  const bool subnormal = ch[2] == '0';
  if ((subnormal || ch[2] == '1') && ch[3] == '.') {
    // ...
  }
}
```

But I'm not sure the `const` offers that much benefit to be worth the slightly worse readability of the code.

**Comment by badasahog** [comment]
the whole point of adding const is to improve readability and clarify intent. adding would seem counterintuitive.
